### ISSUE TITLE
TMux RHS status bar does not work in TMux 2.5

### ISSUE THREAD

**Issue by paulcollingwood2** [matthewfranglen/dotfiles#33]
```
invalid option: utf8
```

Even when removing this it doesn't work.

**Comment by matthewfranglen** [comment]
I am using TMux 2.0 locally. I will upgrade and investigate.

**Comment by matthewfranglen** [comment]
I have installed TMux 2.7 and when I remove the utf8 option a different error occurs:

```
'export PATH=$HOME/.local/bin:$PATH ; $HOME/.local/bin/powerline-config tmux setup >/tmp/tmux.log 2>&1 && rm /tmp/tmux.log' returned 1
```

The content of the log is:

```
➜ cat /tmp/tmux.log 
invalid option: status-utf8
Traceback (most recent call last):
  File "/home/matthew/.local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/home/matthew/.local/lib/python2.7/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/home/matthew/.local/lib/python2.7/site-packages/powerline/bindings/config.py", line 169, in tmux_setup
    source_tmux_files(pl, args)
  File "/home/matthew/.local/lib/python2.7/site-packages/powerline/bindings/config.py", line 71, in source_tmux_files
    run_tmux_command('source', os.path.join(TMUX_CONFIG_DIRECTORY, 'powerline-base.conf'))
  File "/home/matthew/.local/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 32, in run_tmux_command
    _run_tmux(subprocess.check_call, args)
  File "/home/matthew/.local/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 27, in _run_tmux
    return runner([get_tmux_executable_name()] + list(args))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'tmux', u'source', u'/home/matthew/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline-base.conf']' returned non-zero exit status 1
```

**Comment by matthewfranglen** [comment]
I've had to manually edit the file in the error to remove that option. I also tried upgrading the powerline pip package. It's fixed somehow.

May work on this more if that isn't enough to resolve it.
